### ISSUE TITLE
formatUrl converts + to %2B

### ISSUE THREAD

**Issue by dimitarnestorov** [benmvp/url-lib#10]
```javascript
formatUrl("https://accounts.google.com/o/oauth2/auth?client_id=some_id&redirect_uri=some_uri&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.group.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.group.member.readonly&access_type=offline&response_type=code&include_granted_scopes=true&state=connection_id%3Df3a8eba5e5a742cd8a93abe4b1bf5b9b", { redirect_uri: 'some_other_uri' })
```
I'm trying to change `redirect_uri` only but it also changes `scopes` and Google ends up rejecting me for invalid scopes

**Comment by benmvp** [comment]
Wow, sorry @dimitarnestorov! I'm only now seeing this bug from September. I added some tests to `formatUrl` expecting to expose the bug you mentioned, but all the tests passed! You can see them in #14. 

I even ran your example on https://npm.runkit.com/url-lib and it seemed to work correctly. I know it's been 3 months, but if you can share what output you were getting, that'd be helpful in debugging the issue.

For now, I'm going to mark this fixed by #14, but if you find that the bug still exists, we can reopen.
